version: '3.7'

services:
    mysql:
        image: 'mysql:5.7'
        platform: linux/x86_64
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: e-commerce
            MYSQL_USER: test
            MYSQL_PASSWORD: test_pass
            MYSQL_ROOT_HOST: '%'

        volumes:
            - ./database/db_data:/var/lib/mysql
        networks:
            - laravel-nw
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-nw
        depends_on:
            - mysql
networks:
    laravel-nw:
        driver: bridge
